const API='/api';const $=id=>document.getElementById(id);let session=(()=>{try{return JSON.parse(localStorage.getItem('sicbo_v2_session'))}catch{return null}})();
function save(s){session=s;localStorage.setItem('sicbo_v2_session',JSON.stringify(s))}function clear(){session=null;localStorage.removeItem('sicbo_v2_session')}
async function api(url,opt={}){opt.headers={'Content-Type':'application/json',...(opt.headers||{})};if(session?.token)opt.headers.Authorization='Bearer '+session.token;const r=await fetch(API+url,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'REQUEST_FAILED');return j}
function show(s){$('auth').hidden=true;$('game').hidden=false;$('who').textContent=`👤 ${s.character?.name||s.character_name||s.username}`;$('coins').textContent=`🪙 ${Number(s.character?.coins??s.coins??0).toLocaleString('vi-VN')} COIN`;$('adminLink').hidden=!['ADMIN','SUPER_ADMIN'].includes(s.user?.role||s.role);}
function syncFrame(){const f=$('gameFrame');f.onload=()=>{try{f.contentWindow.__SICBO_TOKEN=session.token;const sc=f.contentDocument.createElement('script');sc.src='/bridge.js?v=2';f.contentDocument.head.appendChild(sc)}catch(e){console.error(e)}};if(f.contentDocument?.readyState==='complete')f.onload();}
$('loginTab').onclick=()=>{$('loginTab').classList.add('active');$('registerTab').classList.remove('active');$('loginForm').hidden=false;$('registerForm').hidden=true};$('registerTab').onclick=()=>{$('registerTab').classList.add('active');$('loginTab').classList.remove('active');$('loginForm').hidden=true;$('registerForm').hidden=false};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('msg').textContent='Đang đăng nhập...';try{const j=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('lUser').value,password:$('lPass').value})});save(j);show(j);syncFrame()}catch(e){$('msg').textContent=e.message}};
$('registerForm').onsubmit=async e=>{e.preventDefault();$('msg').textContent='Đang tạo tài khoản...';try{const j=await api('/auth/register',{method:'POST',body:JSON.stringify({username:$('rUser').value,password:$('rPass').value,characterName:$('rName').value})});save(j);show(j);syncFrame()}catch(e){$('msg').textContent=e.message}};
$('logout').onclick=()=>{clear();location.reload()};
(async()=>{if(session?.token){try{const me=await api('/me');session.user={id:me.id,username:me.username,role:me.role,status:me.status};session.character={id:me.character_id,name:me.character_name,level:me.level,exp:me.exp,coins:Number(me.coins)};save(session);show(session);syncFrame()}catch{clear()}}})();
